// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface RepoActivity {
    data: RepoActivityDataData;
}

export interface RepoActivityDataData {
    repository: Repository;
}

export interface Repository {
    id: string;
    isFork: boolean;
    updatedAt: Date;
    pushedAt: Date;
    isArchived: boolean;
    isDisabled: boolean;
    isLocked: boolean;
    issues: NodeInfo;
    pullRequests: NodeInfo;
}

export interface NodeInfo {
    nodes: NodeData[];
}

export interface NodeData {
    updatedAt: Date;
}
