
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    NODE_VERSION: '10.x'      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: 'reports/**/junit.xml'

    - name: SonarCloud Scan
      if: always()
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUDTOKEN }}
      with:
        projectBaseDir: ${{ github.workspace }}

    - name: npm lint
      run: npm run lint

