
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    NODE_VERSION: '10.x'      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run build

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUDTOKEN }}

    - name: npm test
      run: npm run test

    - name: npm lint
      run: npm run lint

